---
- name: Verify Nginx is Listening on Port
  ansible.builtin.shell: "ss -tulpen | grep :443"
  register: nginx_ports
- debug:
    msg: >
      Nginx Listening on Port: 443
  when: nginx_ports.stdout != ""
    
- name: Verify Nginx is Listening on Port
  ansible.builtin.shell: "ss -tulpen | grep :80"
  register: nginx_ports
- debug:
    msg: >
      Nginx Listening on Port: 80
  when: nginx_ports.stdout != ""

- name: Check Nginx Configuration Syntax
  ansible.builtin.shell: "nginx -t"
  register: nginx_config_test
  failed_when: nginx_config_test.rc != 0
    #- debug:
    #msg: "Nginx Configuration Test: {{ nginx_config_test.stdout }}"
- debug:
    msg: >
      Nginx Configuration Syntax is Ok:
  failed_when: nginx_config_test.rc != 0

- name: Ensure Nginx is Active
  ansible.builtin.shell: "systemctl is-active nginx"
  register: nginx_active
- debug:
    msg: "Nginx Activate Status: {{ nginx_active.stdout }}"

- name: Ensure Nginx is Enabled at Boot
  ansible.builtin.shell: "systemctl is-enabled nginx"
  register: nginx_enabled
- debug:
    msg: "Nginx Enabled Status: {{ nginx_enabled.stdout }}"

- name: Check Server Uptime
  ansible.builtin.command:
    cmd: uptime
  register: server_uptime
- debug:
    msg: "Server Uptime: {{ server_uptime.stdout }}"

- name: Ensure Nginx Processes Are Running
  ansible.builtin.shell: "ps aux | grep [n]ginx"
  register: nginx_processes
  ignore_errors: yes  # Allow the task to complete even if it fails

- name: Check if Nginx Processes Variable is Defined
  fail:
    msg: "The nginx_processes variable is undefined. The ps aux command might have failed."
  when: nginx_processes is undefined

- name: Fail if no Nginx processes are found
  fail:
    msg: "No Nginx processes found!"
  when: nginx_processes.stdout == ""

- name: Debug Nginx Processes
  debug:
    msg: >
      Nginx processes are up and running:
  when: nginx_processes.stdout != ""

- name: Optional - Check Nginx Status Code
  ansible.builtin.shell: "curl -LI http://localhost -o /dev/null -w '%{http_code}\n' -s"
  register: status_code
- debug:
    msg: "Nginx Status Code: {{ status_code.stdout }}"

- name: Optional - Check SSL/TLS Certificate Status
  ansible.builtin.shell: "sudo openssl x509 -in /etc/nginx/ssl/fullchain.crt -text -noout | grep 'Not After'"
  register: ssl_cert_status
  ignore_errors: yes
- debug:
    msg: "SSL Certificate Expiry: {{ ssl_cert_status.stdout }}"
...
